namespace Avelia.Core

open System

/// Curated pool of rail/aviation-themed single-word names used to auto-name a
/// new workspace's branch + worktree at creation (no prompt). Sourced from
/// <c>docs/worktree-names.txt</c> and embedded as a constant — the doc is a
/// human reference, not a runtime input. The doc's "don't pick" entries
/// (main / master / trunk / head, and the mournfully-retired sleepers) plus the
/// ⚠️-flagged service names are intentionally excluded so a generated name is
/// never a reserved ref or a loaded reference.
[<RequireQualifiedAccess>]
module WorktreeNames =

    /// The full pool. Lowercased single words, each a valid <c>BranchName</c>
    /// (no whitespace, no leading <c>-</c>, no path separators).
    let all: string array =
        [| // S-tier
           "amfleet"
           "superliner"
           "speedbird"
           "hayabusa"
           "zephyr"
           "shamrock"
           "sapsan"
           "mallard"
           "concorde"
           "foxbat"
           "blackbird"
           "habu"
           "dreamliner"
           "cactus"
           "clipper"
           "dynasty"
           "valkyrie"
           "mistral"
           "ruslan"
           "caravelle"
           "kuroshio"
           // Rolling stock
           "viewliner"
           "horizon"
           "airo"
           "surfliner"
           "genesis"
           "charger"
           "renaissance"
           "venture"
           "azuma"
           "javelin"
           "pendolino"
           "aventra"
           "electrostar"
           "turbostar"
           "networker"
           "voyager"
           "meridian"
           "sprinter"
           "desiro"
           "coradia"
           "movia"
           "velaro"
           "avelia"
           "talgo"
           "giruno"
           "traxx"
           "vectron"
           "inspiro"
           "mireo"
           "talent"
           "regiolis"
           "tangara"
           "waratah"
           "mariyung"
           "matangi"
           "comeng"
           "xtrapolis"
           // Japanese named services
           "komachi"
           "nozomi"
           "hikari"
           "kodama"
           "kagayaki"
           "sakura"
           "mizuho"
           "hayate"
           "tsubasa"
           "tsubame"
           "toki"
           "asama"
           "sonic"
           "kamome"
           "odoriko"
           "yakumo"
           "shiokaze"
           "kamui"
           "soya"
           "ozora"
           "raicho"
           "shirasagi"
           "kirameki"
           "laview"
           "skyliner"
           "spacia"
           // Aviation callsigns
           "springbok"
           "pegasus"
           "volga"
           "logan"
           // NATO reporting names
           "foxhound"
           "fulcrum"
           "flanker"
           "flogger"
           "fishbed"
           "backfire"
           "blinder"
           "blackjack"
           "badger"
           "bear"
           "bison"
           "mainstay"
           "candid"
           "halo"
           "helix"
           "hind"
           "hokum"
           "havoc"
           "classic"
           // Aircraft nicknames
           "hercules"
           "globemaster"
           "galaxy"
           "starlifter"
           "warthog"
           "mustang"
           "spitfire"
           "lightning"
           "thunderbolt"
           "phantom"
           "raptor"
           "viper"
           "hornet"
           "tomcat"
           "prowler"
           "growler"
           "harrier"
           "mirage"
           "typhoon"
           "rafale"
           "gripen"
           "draken"
           "viggen"
           "vulcan"
           "canberra"
           "nimrod"
           "chinook"
           "apache"
           "osprey"
           "valor"
           "connie"
           "tristar"
           "trident"
           "comet"
           "friendship"
           "fellowship"
           "islander"
           "dakota"
           // European train names
           "italo"
           "settebello"
           "frecciarossa"
           "cisalpino"
           "helvetia"
           "rheingold"
           "lastochka"
           "strizh"
           "aurora"
           "nevsky"
           "railjet"
           "nightjet"
           "eurostar"
           // UK named trains
           "scotsman"
           "tornado"
           "jacobite"
           "mancunian"
           "cornishman"
           "bristolian"
           "dragon"
           "riviera"
           "pullman"
           "waverley"
           // Americana
           "acela"
           "cardinal"
           "crescent"
           "adirondack"
           "vermonter"
           "downeaster"
           "pennsylvanian"
           "palmetto"
           "piedmont"
           "borealis"
           "carolinian"
           "hiawatha"
           "wolverine"
           "builder"
           "starlight"
           "sunset"
           "eagle"
           "meteor"
           "lakeshore"
           "capitol"
           "maple"
           "heartland"
           "metroliner"
           "mercury"
           "pacemaker"
           "knickerbocker"
           "pioneer"
           "broadway"
           "daylight"
           "cascade"
           "champion"
           "olympian"
           "wabash"
           "liberty"
           "century"
           "spirit"
           "phoebe"
           // Trams & streetcars
           "tatra"
           "flexity"
           "combino"
           "avenio"
           "cobra"
           "tango"
           "citadis"
           "ulf"
           "mriya" |]

    /// Pick a name not already in <paramref name="used"/>. While the pool has a
    /// free entry, returns a random one; once exhausted it appends the lowest
    /// free <c>-N</c> suffix (<c>-2</c>, <c>-3</c>, …) to a random base name.
    /// Total and never empty: <c>all</c> is non-empty and the suffix search
    /// always terminates against the finite <paramref name="used"/> set.
    let pickUnused (used: Set<string>) (rng: Random) : string =
        let available = all |> Array.filter (fun n -> not (used.Contains n))

        if available.Length > 0 then
            available.[rng.Next available.Length]
        else
            let baseName = all.[rng.Next all.Length]
            let mutable n = 2

            while used.Contains(sprintf "%s-%d" baseName n) do
                n <- n + 1

            sprintf "%s-%d" baseName n
